const STATES = {
  CREATED: 'CREATED',
  INTAKE: 'INTAKE',
  UNDERSTANDING: 'UNDERSTANDING',
  CLASSIFICATION: 'CLASSIFICATION',
  PRIORITY: 'PRIORITY',
  ROUTING: 'ROUTING',
  POLICY_VALIDATION: 'POLICY_VALIDATION',
  DUPLICATE_CHECK: 'DUPLICATE_CHECK',
  DRAFTING: 'DRAFTING',
  QUALITY_REVIEW: 'QUALITY_REVIEW',
  HUMAN_REVIEW: 'HUMAN_REVIEW',
  SUBMITTED: 'SUBMITTED',
  TRACKING: 'TRACKING',
  MONITORING: 'MONITORING',
  RESOLVED: 'RESOLVED',
  ESCALATED: 'ESCALATED',
  REJECTED: 'REJECTED',
  FAILED: 'FAILED'
};

const TIMEOUTS = {
  DEFAULT_LLM: 30000,
  DEFAULT_LOOKUP: 5000,
};

module.exports = {
  STATES,
  TIMEOUTS
};
